/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Order;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author polux
 */
public class PrintableReport extends javax.swing.JPanel implements Printable{
    
    private String initDate;
    private String finalDate;
    /*private Login login = new Login();
    private Main main = new Main(login.person);*/
    
    /**
     * Creates new form Print
     */
    public PrintableReport() {
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiendaReport = new javax.swing.JLabel();
        fechaReport = new javax.swing.JLabel();
        personaReport = new javax.swing.JLabel();
        headerReport = new javax.swing.JLabel();
        articulosReport = new javax.swing.JLabel();
        efectivoLbl = new javax.swing.JLabel();
        tarjetaLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        efectivoReport = new javax.swing.JLabel();
        tarjetaReport = new javax.swing.JLabel();
        totalReport = new javax.swing.JLabel();
        efectivoLbl1 = new javax.swing.JLabel();
        entradaReport = new javax.swing.JLabel();
        tarjetaLbl1 = new javax.swing.JLabel();
        salidaReport = new javax.swing.JLabel();
        efectivoLbl2 = new javax.swing.JLabel();
        refrigerioSalida = new javax.swing.JLabel();
        tarjetaLbl2 = new javax.swing.JLabel();
        refrigerioEntrada = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));

        tiendaReport.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        tiendaReport.setForeground(new java.awt.Color(0, 0, 0));
        tiendaReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiendaReport.setText("tienda");

        fechaReport.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        fechaReport.setForeground(new java.awt.Color(0, 0, 0));
        fechaReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaReport.setText("fechaI - fechaF");

        personaReport.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        personaReport.setForeground(new java.awt.Color(0, 0, 0));
        personaReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personaReport.setText("persona");

        headerReport.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        headerReport.setForeground(new java.awt.Color(0, 0, 0));
        headerReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        headerReport.setText("[Cantidad] [Total] Articulo");

        articulosReport.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        articulosReport.setForeground(new java.awt.Color(0, 0, 0));
        articulosReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        articulosReport.setText("Articulos");
        articulosReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        articulosReport.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        efectivoLbl.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        efectivoLbl.setForeground(new java.awt.Color(0, 0, 0));
        efectivoLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        efectivoLbl.setText("EFECTIVO :");
        efectivoLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tarjetaLbl.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tarjetaLbl.setForeground(new java.awt.Color(0, 0, 0));
        tarjetaLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tarjetaLbl.setText("TARJETA  :");
        tarjetaLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        totalLbl.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        totalLbl.setForeground(new java.awt.Color(0, 0, 0));
        totalLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalLbl.setText("Total    :");
        totalLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        efectivoReport.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        efectivoReport.setForeground(new java.awt.Color(0, 0, 0));
        efectivoReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        efectivoReport.setText("0.00");
        efectivoReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tarjetaReport.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tarjetaReport.setForeground(new java.awt.Color(0, 0, 0));
        tarjetaReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tarjetaReport.setText("0.00");
        tarjetaReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        totalReport.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        totalReport.setForeground(new java.awt.Color(0, 0, 0));
        totalReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalReport.setText("0.00");
        totalReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        efectivoLbl1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        efectivoLbl1.setForeground(new java.awt.Color(0, 0, 0));
        efectivoLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        efectivoLbl1.setText("ENTRADA  :");
        efectivoLbl1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        entradaReport.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        entradaReport.setForeground(new java.awt.Color(0, 0, 0));
        entradaReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        entradaReport.setText("-");
        entradaReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tarjetaLbl1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tarjetaLbl1.setForeground(new java.awt.Color(0, 0, 0));
        tarjetaLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tarjetaLbl1.setText("SALIDA   :");
        tarjetaLbl1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        salidaReport.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        salidaReport.setForeground(new java.awt.Color(0, 0, 0));
        salidaReport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salidaReport.setText("-");
        salidaReport.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        efectivoLbl2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        efectivoLbl2.setForeground(new java.awt.Color(0, 0, 0));
        efectivoLbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        efectivoLbl2.setText("INICIO DESC. :");
        efectivoLbl2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        refrigerioSalida.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        refrigerioSalida.setForeground(new java.awt.Color(0, 0, 0));
        refrigerioSalida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refrigerioSalida.setText("-");
        refrigerioSalida.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tarjetaLbl2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tarjetaLbl2.setForeground(new java.awt.Color(0, 0, 0));
        tarjetaLbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tarjetaLbl2.setText("FIN DESCANSO :");
        tarjetaLbl2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        refrigerioEntrada.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        refrigerioEntrada.setForeground(new java.awt.Color(0, 0, 0));
        refrigerioEntrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refrigerioEntrada.setText("-");
        refrigerioEntrada.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tiendaReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personaReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(articulosReport, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(efectivoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(efectivoReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarjetaLbl)
                            .addComponent(totalLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarjetaReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(headerReport, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tarjetaLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salidaReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(efectivoLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(efectivoLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refrigerioSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tarjetaLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refrigerioEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tiendaReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personaReport)
                .addGap(18, 18, 18)
                .addComponent(headerReport, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(articulosReport)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(efectivoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(efectivoReport))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarjetaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarjetaReport, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalReport, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(efectivoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entradaReport))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarjetaLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salidaReport, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(efectivoLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refrigerioSalida))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarjetaLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrigerioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        articulosReport.getAccessibleContext().setAccessibleName("articulos");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel articulosReport;
    private javax.swing.JLabel efectivoLbl;
    private javax.swing.JLabel efectivoLbl1;
    private javax.swing.JLabel efectivoLbl2;
    private javax.swing.JLabel efectivoReport;
    private javax.swing.JLabel entradaReport;
    private javax.swing.JLabel fechaReport;
    private javax.swing.JLabel headerReport;
    private javax.swing.JLabel personaReport;
    private javax.swing.JLabel refrigerioEntrada;
    private javax.swing.JLabel refrigerioSalida;
    private javax.swing.JLabel salidaReport;
    private javax.swing.JLabel tarjetaLbl;
    private javax.swing.JLabel tarjetaLbl1;
    private javax.swing.JLabel tarjetaLbl2;
    private javax.swing.JLabel tarjetaReport;
    private javax.swing.JLabel tiendaReport;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JLabel totalReport;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex == 0) {
            Graphics2D graphics2d = (Graphics2D) graphics;
            graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            graphics2d.scale(pageFormat.getImageableWidth() / this.getWidth(), pageFormat.getImageableWidth() / this.getWidth());
            this.printAll(graphics2d);
            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }
}
