/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Order;

import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Pageable;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author polux
 */
public class Print extends javax.swing.JFrame {

    /**
     * Creates new form Print
     */
    public Print() {
        //initComponents();
        setLocationRelativeTo(null);
        //printableReport1.fillArticulos(person, initDate, finalDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        printAccept = new javax.swing.JButton();
        exitPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(320, 500));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(320, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 500));

        printAccept.setText("Imprimir");
        printAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAcceptActionPerformed(evt);
            }
        });
        jPanel1.add(printAccept);

        exitPrint.setText("Cancelar");
        exitPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPrintActionPerformed(evt);
            }
        });
        jPanel1.add(exitPrint);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAcceptActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();

        // --- CONFIGURACIÓN DEL PAPEL ---
        PageFormat pf = job.defaultPage();
        Paper paper = pf.getPaper();

        // Tamaño del papel (en puntos; 1 pulgada = 72 puntos)
        double width = 80 / 25.4 * 72;   // 80 mm a puntos
        double height = 3276 / 25.4 * 72; // 290 mm a puntos

        paper.setSize(width, height);

        // Área imprimible: todo el papel (sin márgenes)
        paper.setImageableArea(0, 0, width, height);

        pf.setPaper(paper);

        // --- ASIGNAR EL PRINTABLE CON TU PAGEFORMAT ---
        job.setPrintable(printableReport1, pf);

        // --- DIÁLOGO DE IMPRESIÓN ---
        if (job.printDialog()) {
            try {
                job.setJobName("Reporte Ventas KyC");
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(Print.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "La impresión se canceló");
        }

    }//GEN-LAST:event_printAcceptActionPerformed

    private void exitPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPrintActionPerformed
        dispose();
    }//GEN-LAST:event_exitPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitPrint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printAccept;
    // End of variables declaration//GEN-END:variables
}
